# Generated by Django 3.1.7 on 2021-03-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256)),
                ('date_birth', models.DateField()),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBody',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='body', serialize=False, to='api_doc_flow.document')),
                ('body', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, choices=[(2, 'In progress'), (3, 'Done'), (1, 'Start')], null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_doc_flow.patient')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_doc_flow.patient'),
        ),
        migrations.AddField(
            model_name='document',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api_doc_flow.treatment'),
        ),
    ]
